<#
.SYNOPSIS
    Builds one XSLT template per InfoPath grouping and writes a group-to-template mapping CSV.

.DESCRIPTION
    Reads the detailed CSV output from AnalyzeInfoPathGroupingFromCsv.ps1, selects one
    sample XML file per SuggestedGroup, invokes CreateXSLTfromInfopathFile.ps1 to generate
    the XSLT/CSS assets, and writes a separate CSV that maps each SuggestedGroup to the
    template files that should be used for that group.
    Grouping is expected to be TemplateVersion-based.

.PARAMETER GroupingCsvPath
    Path to the detailed CSV generated by AnalyzeInfoPathGroupingFromCsv.ps1.

.PARAMETER TemplateOutputDirectory
    Folder where generated XSLT/CSS/log files will be written.

.PARAMETER MappingCsvPath
    Path to the output CSV that maps SuggestedGroup to the generated XSLT template.
    Default: <TemplateOutputDirectory>\InfoPathXsltGroupMap.csv

.PARAMETER CreateXsltScriptPath
    Path to CreateXSLTfromInfopathFile.ps1.
    Default: sibling script in the current script directory.

.EXAMPLE
    .\BuildXsltFromGroupingCsv.ps1 `
      -GroupingCsvPath "C:\Save\Reports\InfoPathGroupingDetailed.csv" `
      -TemplateOutputDirectory "C:\Save\Templates"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$GroupingCsvPath,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TemplateOutputDirectory,

    [string]$MappingCsvPath,

    [string]$CreateXsltScriptPath = (Join-Path -Path $PSScriptRoot -ChildPath 'CreateXSLTfromInfopathFile.ps1')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-LogEntry {
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [System.Collections.Generic.List[string]]$LogEntries,

        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $LogEntries.Add("[$timestamp] $Message") | Out-Null
}

function Write-Stage {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [ValidateSet('Init', 'Input', 'Select', 'Build', 'Write', 'Done', 'Warn', 'Error')]
        [string]$Group = 'Build'
    )

    $color = switch ($Group) {
        'Init' { 'Cyan' }
        'Input' { 'DarkCyan' }
        'Select' { 'Yellow' }
        'Build' { 'White' }
        'Write' { 'Green' }
        'Done' { 'Magenta' }
        'Warn' { 'DarkYellow' }
        'Error' { 'Red' }
        default { 'White' }
    }

    Write-Host "[$Group] $Message" -ForegroundColor $color
}

function Convert-ToSafeFileStem {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    $safe = $Value
    foreach ($char in [System.IO.Path]::GetInvalidFileNameChars()) {
        $safe = $safe.Replace($char, '-')
    }

    $safe = ($safe -replace '\s+', '_').Trim('_')
    if ([string]::IsNullOrWhiteSpace($safe)) {
        return 'unnamed'
    }

    return $safe
}

function Get-RequiredValue {
    param(
        [Parameter(Mandatory = $true)]
        [psobject]$Row,

        [Parameter(Mandatory = $true)]
        [string]$PropertyName
    )

    $property = $Row.PSObject.Properties[$PropertyName]
    if ($null -eq $property) {
        throw "Input CSV is missing required column '$PropertyName'."
    }

    return [string]$property.Value
}

function Get-FieldCountValue {
    param(
        [Parameter(Mandatory = $true)]
        [psobject]$Row
    )

    $fieldCount = 0
    $parsed = [int]::TryParse([string]$Row.FieldCount, [ref]$fieldCount)
    if ($parsed) {
        return $fieldCount
    }

    return 0
}

if (-not (Test-Path -LiteralPath $GroupingCsvPath -PathType Leaf)) {
    throw "GroupingCsvPath does not exist: $GroupingCsvPath"
}

if (-not (Test-Path -LiteralPath $CreateXsltScriptPath -PathType Leaf)) {
    throw "CreateXsltScriptPath does not exist: $CreateXsltScriptPath"
}

if (-not (Test-Path -LiteralPath $TemplateOutputDirectory -PathType Container)) {
    New-Item -Path $TemplateOutputDirectory -ItemType Directory -Force | Out-Null
}

if ([string]::IsNullOrWhiteSpace($MappingCsvPath)) {
    $MappingCsvPath = Join-Path -Path $TemplateOutputDirectory -ChildPath 'InfoPathXsltGroupMap.csv'
}

$mappingDirectory = Split-Path -Path $MappingCsvPath -Parent
if (-not [string]::IsNullOrWhiteSpace($mappingDirectory) -and -not (Test-Path -LiteralPath $mappingDirectory -PathType Container)) {
    New-Item -Path $mappingDirectory -ItemType Directory -Force | Out-Null
}

$logEntries = New-Object System.Collections.Generic.List[string]
$startTime = Get-Date

Write-Stage -Group Init -Message 'Starting XSLT generation from grouping CSV.'
Write-Stage -Group Input -Message "Grouping CSV: $GroupingCsvPath"
Write-Stage -Group Input -Message "Template output directory: $TemplateOutputDirectory"
Write-Stage -Group Input -Message "Mapping CSV: $MappingCsvPath"
Write-Stage -Group Input -Message "CreateXSLT script: $CreateXsltScriptPath"

Write-LogEntry -LogEntries $logEntries -Message 'Started XSLT generation from grouping CSV.'
Write-LogEntry -LogEntries $logEntries -Message "GroupingCsvPath=$GroupingCsvPath"
Write-LogEntry -LogEntries $logEntries -Message "TemplateOutputDirectory=$TemplateOutputDirectory"
Write-LogEntry -LogEntries $logEntries -Message "MappingCsvPath=$MappingCsvPath"
Write-LogEntry -LogEntries $logEntries -Message "CreateXsltScriptPath=$CreateXsltScriptPath"

$rows = @(Import-Csv -LiteralPath $GroupingCsvPath)
if ($rows.Count -eq 0) {
    throw "Grouping CSV contains no rows: $GroupingCsvPath"
}

Write-Stage -Group Input -Message "Loaded $($rows.Count) row(s) from grouping CSV."

$successfulRows = @(
    $rows |
        Where-Object {
            ([string]$_.ParseStatus) -eq 'Success' -and
            -not [string]::IsNullOrWhiteSpace([string]$_.SuggestedGroup) -and
            ([string]$_.SuggestedGroup) -ne 'ParseFailed'
        }
)

if ($successfulRows.Count -eq 0) {
    throw 'No successful grouped rows were found in the grouping CSV.'
}

$mappingRows = New-Object System.Collections.Generic.List[object]

$groupedRows = @(
    $successfulRows |
        Group-Object -Property SuggestedGroup |
        Sort-Object Name
)

Write-Stage -Group Select -Message "Found $($groupedRows.Count) group(s) eligible for XSLT generation."

foreach ($group in $groupedRows) {
    $groupRows = @($group.Group)
    $sampleRow = @(
        $groupRows |
            Sort-Object @(
                @{ Expression = { Get-FieldCountValue -Row $_ }; Descending = $true },
                @{ Expression = { [string]$_.SourceFileName }; Descending = $false }
            ) |
            Select-Object -First 1
    )[0]
    $sampleSourceFilePath = Get-RequiredValue -Row $sampleRow -PropertyName 'SourceFilePath'
    $sampleSourceFileName = Get-RequiredValue -Row $sampleRow -PropertyName 'SourceFileName'
    $suggestedGroup = Get-RequiredValue -Row $sampleRow -PropertyName 'SuggestedGroup'
    $sampleFieldCount = Get-FieldCountValue -Row $sampleRow

    $templateVersionNorm = [string]$sampleRow.TemplateVersionNorm
    if ([string]::IsNullOrWhiteSpace($templateVersionNorm)) {
        $templateVersionNorm = [string]$sampleRow.TemplateVersion
    }
    if ([string]::IsNullOrWhiteSpace($templateVersionNorm)) {
        $templateVersionNorm = 'UnknownVersion'
    }

    $safeTemplateVersion = Convert-ToSafeFileStem -Value $templateVersionNorm
    
    # Use only the first 3 version segments (major.minor.patch) for the second part
    # to avoid duplication when the full version has 4+ segments (major.minor.patch.build)
    $versionParts = $templateVersionNorm -split '\.'
    if ($versionParts.Count -gt 3) {
        $templateVersionShort = ($versionParts[0..2] -join '.')
    }
    else {
        $templateVersionShort = $templateVersionNorm
    }
    $safeTemplateVersionShort = Convert-ToSafeFileStem -Value $templateVersionShort
    
    $outputName = "tmpl__{0}__{1}" -f $safeTemplateVersion, $safeTemplateVersionShort
    $expectedXsltPath = Join-Path -Path $TemplateOutputDirectory -ChildPath ($outputName + '.xslt')
    $expectedCssPath = Join-Path -Path $TemplateOutputDirectory -ChildPath ($outputName + '.css')
    $expectedLogPath = Join-Path -Path $TemplateOutputDirectory -ChildPath ($outputName + '.log')

    Write-Stage -Group Select -Message "Selected sample for group '$suggestedGroup': $sampleSourceFileName (FieldCount=$sampleFieldCount)"
    Write-LogEntry -LogEntries $logEntries -Message "Selected sample '$sampleSourceFilePath' for group '$suggestedGroup' with FieldCount=$sampleFieldCount."

    $generationStatus = 'Success'
    $generationError = $null

    $actualXsltPath = $null
    $actualCssPath = $null
    $actualLogPath = $null

    try {
        Write-Stage -Group Build -Message "Generating XSLT for group '$suggestedGroup'."
        $output = & $CreateXsltScriptPath -InfoPathXmlPath $sampleSourceFilePath -OutputName $outputName -OutputDirectory $TemplateOutputDirectory 2>&1
        
        # Extract actual file paths from script output
        $resultMatch = $output | Select-String -Pattern '##TEMPLATE_GENERATION_RESULT##(.+?)##END_RESULT##'
        if ($resultMatch) {
            $resultJson = $resultMatch.Matches[0].Groups[1].Value
            $result = ConvertFrom-Json -InputObject $resultJson
            $actualXsltPath = $result.XsltPath
            $actualCssPath = $result.CssPath
            $actualLogPath = $result.LogPath
            
            # Verify actual paths match expected paths
            if ($actualXsltPath -ne $expectedXsltPath) {
                Write-Stage -Group Warn -Message "Path mismatch for group '$suggestedGroup': Expected '$expectedXsltPath' but got '$actualXsltPath'"
                Write-LogEntry -LogEntries $logEntries -Message "WARNING: Path mismatch for group '$suggestedGroup' :: Expected='$expectedXsltPath' Actual='$actualXsltPath'"
            }
        }
        else {
            # Fallback: assume expected paths are correct
            $actualXsltPath = $expectedXsltPath
            $actualCssPath = $expectedCssPath
            $actualLogPath = $expectedLogPath
        }

        foreach ($generatedPath in @($actualXsltPath, $actualCssPath, $actualLogPath)) {
            if ([string]::IsNullOrWhiteSpace([string]$generatedPath) -or -not (Test-Path -LiteralPath $generatedPath -PathType Leaf)) {
                throw "Template generator reported success but did not create the expected file: $generatedPath"
            }
        }
        
        Write-LogEntry -LogEntries $logEntries -Message "Generated XSLT for group '$suggestedGroup' => '$actualXsltPath'."
    }
    catch {
        $generationStatus = 'Failed'
        $generationError = $_.Exception.Message
        Write-Stage -Group Warn -Message "XSLT generation failed for group '$suggestedGroup'."
        Write-Stage -Group Error -Message $generationError
        Write-LogEntry -LogEntries $logEntries -Message "ERROR: XSLT generation failed for group '$suggestedGroup' :: $generationError"
    }

    $mappingRows.Add([pscustomobject]@{
        SuggestedGroup        = $suggestedGroup
        FileCountInGroup      = $groupRows.Count
        TemplateVersionNorm   = $templateVersionNorm
        SampleFieldCount      = $sampleFieldCount
        SampleSourceFilePath  = $sampleSourceFilePath
        SampleSourceFileName  = $sampleSourceFileName
        XsltOutputName        = $outputName
        XsltPath              = if ($generationStatus -eq 'Success') { $actualXsltPath } else { $null }
        CssPath               = if ($generationStatus -eq 'Success') { $actualCssPath } else { $null }
        GeneratorLogPath      = if ($generationStatus -eq 'Success') { $actualLogPath } else { $null }
        GenerationStatus      = $generationStatus
        GenerationError       = $generationError
    })
}

Write-Stage -Group Write -Message 'Writing group-to-template mapping CSV.'
$mappingRows | Export-Csv -Path $MappingCsvPath -NoTypeInformation -Encoding UTF8

$orchestrationLogPath = [System.IO.Path]::ChangeExtension($MappingCsvPath, '.log')
$duration = (Get-Date) - $startTime
Write-LogEntry -LogEntries $logEntries -Message "Completed. Duration=$($duration.ToString())"
Write-LogEntry -LogEntries $logEntries -Message ("Summary: Groups={0}, SuccessfulTemplates={1}, FailedTemplates={2}" -f $mappingRows.Count, (@($mappingRows | Where-Object { $_.GenerationStatus -eq 'Success' })).Count, (@($mappingRows | Where-Object { $_.GenerationStatus -ne 'Success' })).Count)
$logEntries | Set-Content -LiteralPath $orchestrationLogPath -Encoding UTF8

Write-Stage -Group Done -Message 'Completed XSLT generation from grouping CSV.'
Write-Host "Mapping CSV       : $MappingCsvPath" -ForegroundColor Magenta
Write-Host "Orchestration log : $orchestrationLogPath" -ForegroundColor Magenta
