<#
.SYNOPSIS
	Extracts normalized properties from InfoPath XML files into multiple CSVs using version-specific structure configs.

.DESCRIPTION
	Reads InfoPath XML files and normalizes data into multiple tables (Main + repeating groups)
	based on structure metadata from ProcessInfoPathAnalyze.ps1.

	Completely generic—no assumptions about document type or element names. Data structure
	is driven by StructureReport_[Version].json files generated by the analyzer.

	Supports two modes:
	  1. Version-aware extraction: Uses VersioningCsvPath + AnalysisDirectory to load version-specific configs
	  2. Single-config extraction: Uses StructureConfigPath for all files
	  3. Auto-analysis (fallback): Analyzes source files if no config provided

	Outputs to OutputDirectory/Normalized/:
	  - Main.csv: Non-repeating fields
	  - <GroupName>.csv: One CSV per repeating group detected
	  - PropertyMapping.csv: Mapping of shortened names to original XPaths
	  - ProcessingReport.txt: Statistics and diagnostics

.PARAMETER SourceDirectory
	Root folder containing InfoPath XML files to extract.

.PARAMETER OutputDirectory
	Directory where normalized CSVs will be written (output goes to Normalized/ subdirectory).

.PARAMETER VersioningCsvPath
	(Optional) Path to versioning CSV from ClassifyInfoPathVersions.ps1.
	Must have columns: TemplateVersion/TemplateName and SourceFilePath/FileName.
	If provided with AnalysisDirectory, enables version-based config loading.

.PARAMETER AnalysisDirectory
	(Optional) Directory containing version-specific StructureReport_[Version].json files.
	Required when using VersioningCsvPath. Created by ProcessInfoPathAnalyze.ps1 with versioning.

.PARAMETER StructureConfigPath
	(Optional) Path to single StructureReport.json for all files.
	Ignored if VersioningCsvPath + AnalysisDirectory provided.
	If omitted, runs auto-analysis on source files (slower, one-time cost).

.PARAMETER Recurse
	Include subfolders when discovering XML files.

.EXAMPLE
	# Version-based extraction (recommended for multi-version documents)
	.\ProcessInfoPathAnalyze.ps1 `
	  -SourceDirectory "C:\Samples" `
	  -OutputDirectory "C:\Analysis" `
	  -VersioningCsvPath "C:\Reports\InfoPathVersionMap.csv"

	.\ProcessInfoPathProperties.ps1 `
	  -SourceDirectory "C:\AllDocuments" `
	  -OutputDirectory "C:\Reports" `
	  -VersioningCsvPath "C:\Reports\InfoPathVersionMap.csv" `
	  -AnalysisDirectory "C:\Analysis"

.EXAMPLE
	# Single-config extraction (all files use same structure)
	.\ProcessInfoPathProperties.ps1 `
	  -SourceDirectory "C:\AllDocuments" `
	  -OutputDirectory "C:\Reports" `
	  -StructureConfigPath "C:\Analysis\StructureReport.json"

.EXAMPLE
	# Quick extraction without separate analysis (auto-detects structure)
	.\ProcessInfoPathProperties.ps1 `
	  -SourceDirectory "C:\AllDocuments" `
	  -OutputDirectory "C:\Reports" `
	  -Recurse

.NOTES
	Generic extraction pipeline—works on any InfoPath document type.
	For multi-version documents, use VersioningCsvPath + AnalysisDirectory for version-specific handling.
	For single document type, use -StructureConfigPath for optimal performance.
#>

[CmdletBinding()]
param(
	# Folder that contains InfoPath XML files.
	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$SourceDirectory,

	# Output directory where normalized CSVs will be written.
	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$OutputDirectory,

	# (Optional) Path to versioning CSV from ClassifyInfoPathVersions.ps1
	[string]$VersioningCsvPath = $null,

	# (Optional) Directory containing version-specific StructureReport_[Version].json files
	[string]$AnalysisDirectory = $null,

	# (Optional) Path to StructureReport.json from analyzer (used if versioning not provided)
	[string]$StructureConfigPath = $null,

	# Include subfolders when searching for XML files.
	[switch]$Recurse
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Stage {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Message,

		[ValidateSet("Init", "Input", "Parse", "Extract", "Map", "Write", "Done", "Warn", "Error")]
		[string]$Group = "Parse"
	)

	$color = switch ($Group) {
		"Init" { "Cyan" }
		"Input" { "DarkCyan" }
		"Parse" { "Yellow" }
		"Extract" { "Gray" }
		"Map" { "Blue" }
		"Write" { "Green" }
		"Done" { "Magenta" }
		"Warn" { "DarkYellow" }
		"Error" { "Red" }
		default { "White" }
	}

	Write-Host "[$Group] $Message" -ForegroundColor $color
}

# Build version index from versioning CSV
function New-VersionIndex {
	param(
		[Parameter(Mandatory = $true)]
		[object[]]$VersionRows
	)

	$index = @{}
	foreach ($row in $VersionRows) {
		$version = $null
		$filePath = $null

		# Find version column
		foreach ($col in @("TemplateVersion", "TemplateName", "Version", "Group")) {
			if ($null -ne $row.$col -and -not [string]::IsNullOrWhiteSpace($row.$col)) {
				$version = $row.$col
				break
			}
		}

		# Find filepath column
		foreach ($col in @("SourceFilePath", "FilePath", "FileName", "Name")) {
			if ($null -ne $row.$col -and -not [string]::IsNullOrWhiteSpace($row.$col)) {
				$filePath = $row.$col
				break
			}
		}

		if ($null -ne $version -and -not [string]::IsNullOrWhiteSpace($filePath)) {
			$fileName = [System.IO.Path]::GetFileName($filePath)
			$key = $fileName.ToLowerInvariant()
			$index[$key] = $version
		}
	}

	return $index
}

# Resolve a file's version from the version index
function Resolve-FileVersion {
	param(
		[Parameter(Mandatory = $true)]
		[System.IO.FileInfo]$XmlFile,

		[Parameter(Mandatory = $true)]
		[hashtable]$VersionIndex
	)

	$key = $XmlFile.Name.ToLowerInvariant()
	return $VersionIndex[$key]
}

# Abbreviated name logic (consistent with analyzer/reporter)
function Get-AbbreviatedName {
	param(
		[Parameter(Mandatory = $true)]
		[string]$OriginalPath
	)

	$parts = @()
	foreach ($segment in ($OriginalPath -split '/')) {
		if ([string]::IsNullOrWhiteSpace($segment)) { continue }
		
		$segment = $segment -replace '^[a-z]+:', ''
		if ($segment -like '@*') {
			$segment = $segment -replace '@[a-z]+:', '@'
		}
		
		$abbrev = $segment `
			-replace 'Application', 'App' `
			-replace 'Section', 'Sec' `
			-replace 'Attachments?', 'Attach' `
			-replace 'Additional', 'Addl' `
			-replace 'Information', 'Info' `
			-replace 'Document', 'Doc' `
			-replace 'Prosecutor', 'Pros' `
			-replace 'Assistant', 'Asst' `
			-replace 'Fingerprint', 'FP' `
			-replace 'Wanted', 'Wnt' `
			-replace 'Person', 'Pers' `
			-replace 'Entry', 'Ent' `
			-replace 'Description', 'Desc' `
			-replace 'Nationality', 'Nat' `
			-replace 'Citizenship', 'Cit' `
			-replace 'Address', 'Addr' `
			-replace 'Contact', 'Ctc' `
			-replace 'Charge', 'Ch' `
			-replace 'Count', 'Cnt' `
			-replace 'Court', 'Ct' `
			-replace 'Physical', 'Phys' `
			-replace 'Distinguishing', 'Dist' `
			-replace 'Characteristic', 'Char' `
			-replace 'Height', 'Ht' `
			-replace 'Weight', 'Wt' `
			-replace 'Language', 'Lang' `
			-replace 'Marks', 'Mrk' `
			-replace 'Organization', 'Org' `
			-replace 'Employment', 'Emp' `
			-replace 'Agency', 'Agcy' `
			-replace 'File', 'Fl' `
			-replace 'Show', 'Sh' `
			-replace 'Request', 'Req' `
			-replace 'Complete', 'Cmplt' `
			-replace 'Name', 'Nm' `
			-replace 'Build', 'Bld' `
			-replace 'Color', 'Col'
		
		$parts += $abbrev
	}

	return $parts -join '/'
}

# Get child elements respecting StrictMode
function Get-ElementChildren {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node
	)

	return ,@($Node.ChildNodes | Where-Object { $_.NodeType -eq [System.Xml.XmlNodeType]::Element })
}

# Recursively extract values from XML node
function Add-XmlNodeValues {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node,

		[Parameter(Mandatory = $true)]
		[string]$Path,

		[Parameter(Mandatory = $true)]
		[hashtable]$Map
	)

	if ($null -ne $Node.Attributes) {
		foreach ($attribute in $Node.Attributes) {
			$key = "$Path/@$($attribute.Name)"
			if ($Map.ContainsKey($key)) {
				if ($Map[$key] -notlike "*$($attribute.Value)*") {
					$Map[$key] = "$($Map[$key]); $($attribute.Value)"
				}
			}
			else {
				$Map[$key] = $attribute.Value
			}
		}
	}

	$elementChildren = Get-ElementChildren -Node $Node

	if ($elementChildren.Count -eq 0) {
		$value = $Node.InnerText.Trim()
		if (-not [string]::IsNullOrWhiteSpace($value)) {
			$key = $Path
			if ($Map.ContainsKey($key)) {
				if ($Map[$key] -notlike "*$value*") {
					$Map[$key] = "$($Map[$key]); $value"
				}
			}
			else {
				$Map[$key] = $value
			}
		}
		return
	}

	$nameCounts = @{}
	foreach ($child in $elementChildren) {
		if ($nameCounts.ContainsKey($child.Name)) {
			$nameCounts[$child.Name]++
		}
		else {
			$nameCounts[$child.Name] = 1
		}
	}

	$nameIndexes = @{}
	foreach ($child in $elementChildren) {
		if ($nameIndexes.ContainsKey($child.Name)) {
			$nameIndexes[$child.Name]++
		}
		else {
			$nameIndexes[$child.Name] = 1
		}

		$childPath = "$Path/$($child.Name)"
		if ($nameCounts[$child.Name] -gt 1) {
			$childPath = "$childPath[$($nameIndexes[$child.Name])]"
		}

		Add-XmlNodeValues -Node $child -Path $childPath -Map $Map
	}
}

function Get-RelativePath {
	param(
		[Parameter(Mandatory = $true)]
		[string]$BasePath,
		[Parameter(Mandatory = $true)]
		[string]$FullPath
	)

	$basePath = [System.IO.Path]::GetFullPath($BasePath).TrimEnd(
		[System.IO.Path]::DirectorySeparatorChar,
		[System.IO.Path]::AltDirectorySeparatorChar
	)
	$fullPath = [System.IO.Path]::GetFullPath($FullPath)

	try {
		$baseUri = New-Object System.Uri($basePath + [System.IO.Path]::DirectorySeparatorChar)
		$fullUri = New-Object System.Uri($fullPath)
		$relativeUri = $baseUri.MakeRelativeUri($fullUri)
		return [System.Uri]::UnescapeDataString($relativeUri.ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
	}
	catch {
		return [System.IO.Path]::GetFileName($FullPath)
	}
}

function Convert-ToSafeFileName {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Value
	)

	$safe = $Value
	foreach ($invalid in [System.IO.Path]::GetInvalidFileNameChars()) {
		$safe = $safe.Replace($invalid, '_')
	}

	$safe = ($safe -replace '[\s]+', '_').Trim('_')
	if ([string]::IsNullOrWhiteSpace($safe)) {
		return 'attachment'
	}

	return $safe
}

function Get-NodeChildElements {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node
	)

	return ,@($Node.ChildNodes | Where-Object { $_.NodeType -eq [System.Xml.XmlNodeType]::Element })
}

function Try-DecodeInfoPathAttachment {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyString()]
		[string]$Value
	)

	if ([string]::IsNullOrWhiteSpace($Value)) {
		return $null
	}

	$candidate = $Value.Trim()
	if ($candidate.Length -lt 64 -or ($candidate -notmatch '^[A-Za-z0-9+/=\r\n]+$')) {
		return $null
	}

	try {
		$bytes = [System.Convert]::FromBase64String($candidate)
	}
	catch {
		return $null
	}

	if ($bytes.Length -lt 28) {
		return $null
	}

	if ($bytes[0] -ne 0xC7 -or $bytes[1] -ne 0x49 -or $bytes[2] -ne 0x46 -or $bytes[3] -ne 0x41) {
		return $null
	}

	$stream = [System.IO.MemoryStream]::new($bytes)
	$reader = [System.IO.BinaryReader]::new($stream)

	try {
		$null = $reader.ReadBytes(16)
		$fileSize = $reader.ReadUInt32()
		$fileNameCharacterCount = $reader.ReadUInt32()

		if ($fileNameCharacterCount -lt 1 -or $fileNameCharacterCount -gt [int]::MaxValue / 2) {
			return $null
		}

		$fileNameByteLength = [int]$fileNameCharacterCount * 2
		if ($fileNameByteLength -gt ($bytes.Length - 24)) {
			return $null
		}

		$fileNameBytes = $reader.ReadBytes($fileNameByteLength)
		if ($fileNameBytes.Length -lt $fileNameByteLength) {
			return $null
		}

		$decodedName = [System.Text.Encoding]::Unicode.GetString($fileNameBytes)
		$decodedName = $decodedName.Trim([char]0)
		if ([string]::IsNullOrWhiteSpace($decodedName)) {
			$decodedName = 'attachment.bin'
		}

		$remaining = [int]($stream.Length - $stream.Position)
		if ($remaining -le 0) {
			return $null
		}

		$bytesToRead = [Math]::Min([int]$fileSize, $remaining)
		if ($bytesToRead -le 0) {
			$bytesToRead = $remaining
		}

		$fileBytes = $reader.ReadBytes($bytesToRead)
		if ($fileBytes.Length -eq 0) {
			return $null
		}

		return @{
			FileName = [System.IO.Path]::GetFileName($decodedName)
			Content  = $fileBytes
		}
	}
	catch {
		return $null
	}
	finally {
		$reader.Dispose()
		$stream.Dispose()
	}
}

function New-UniqueAttachmentPath {
	param(
		[Parameter(Mandatory = $true)]
		[string]$DirectoryPath,
		[Parameter(Mandatory = $true)]
		[string]$DesiredName
	)

	$baseName = [System.IO.Path]::GetFileNameWithoutExtension($DesiredName)
	$extension = [System.IO.Path]::GetExtension($DesiredName)
	if ([string]::IsNullOrWhiteSpace($extension)) {
		$extension = '.bin'
	}

	$safeBase = Convert-ToSafeFileName -Value $baseName
	$candidate = Join-Path -Path $DirectoryPath -ChildPath ($safeBase + $extension)
	$counter = 1

	while (Test-Path -LiteralPath $candidate -PathType Leaf) {
		$candidate = Join-Path -Path $DirectoryPath -ChildPath ("{0}_{1}{2}" -f $safeBase, $counter, $extension)
		$counter++
	}

	return $candidate
}

function Expand-EmbeddedAttachments {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node,
		[Parameter(Mandatory = $true)]
		[string]$AttachmentOutputDirectory,
		[Parameter(Mandatory = $true)]
		[string]$RelativePrefix
	)

	$children = Get-NodeChildElements -Node $Node
	if ($children.Count -eq 0) {
		$decodedAttachment = Try-DecodeInfoPathAttachment -Value $Node.InnerText
		if ($null -eq $decodedAttachment) {
			return 0
		}

		$desiredName = if ([string]::IsNullOrWhiteSpace($decodedAttachment.FileName)) { 'attachment.bin' } else { $decodedAttachment.FileName }
		$targetFilePath = New-UniqueAttachmentPath -DirectoryPath $AttachmentOutputDirectory -DesiredName $desiredName
		[System.IO.File]::WriteAllBytes($targetFilePath, $decodedAttachment.Content)

		$fileName = [System.IO.Path]::GetFileName($targetFilePath)
		$relativePath = "{0}/{1}" -f $RelativePrefix.TrimEnd('/'), $fileName
		$Node.InnerText = "ATTACHMENT::$relativePath"
		return 1
	}

	$count = 0
	foreach ($child in $children) {
		$count += Expand-EmbeddedAttachments -Node $child -AttachmentOutputDirectory $AttachmentOutputDirectory -RelativePrefix $RelativePrefix
	}

	return $count
}

function Get-MimeTypeFromPath {
	param(
		[Parameter(Mandatory = $true)]
		[string]$FilePath
	)

	$extension = [System.IO.Path]::GetExtension($FilePath).ToLowerInvariant()

	$mimeTypes = @{
		'.pdf'  = 'application/pdf'
		'.doc'  = 'application/msword'
		'.docx' = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
		'.xls'  = 'application/vnd.ms-excel'
		'.xlsx' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
		'.ppt'  = 'application/vnd.ms-powerpoint'
		'.pptx' = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
		'.txt'  = 'text/plain'
		'.csv'  = 'text/csv'
		'.xml'  = 'application/xml'
		'.jpg'  = 'image/jpeg'
		'.jpeg' = 'image/jpeg'
		'.png'  = 'image/png'
		'.gif'  = 'image/gif'
		'.tif'  = 'image/tiff'
		'.tiff' = 'image/tiff'
		'.bmp'  = 'image/bmp'
		'.zip'  = 'application/zip'
		'.msg'  = 'application/vnd.ms-outlook'
	}

	if ($mimeTypes.ContainsKey($extension)) {
		return $mimeTypes[$extension]
	}

	return 'application/octet-stream'
}

function Resolve-AttachmentMetadata {
	param(
		[Parameter(Mandatory = $false)]
		[AllowNull()]
		[string]$Value,
		[Parameter(Mandatory = $true)]
		[string]$AttachmentBaseDirectory
	)

	if ([string]::IsNullOrWhiteSpace($Value) -or -not $Value.StartsWith('ATTACHMENT::')) {
		return $null
	}

	$relativePath = $Value.Substring('ATTACHMENT::'.Length)
	$normalizedRelative = $relativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
	$attachmentPath = Join-Path -Path $AttachmentBaseDirectory -ChildPath $normalizedRelative

	if (-not (Test-Path -LiteralPath $attachmentPath -PathType Leaf)) {
		return [pscustomobject]@{
			SizeBytes = $null
			MimeType  = Get-MimeTypeFromPath -FilePath $attachmentPath
		}
	}

	$fileInfo = Get-Item -LiteralPath $attachmentPath
	return [pscustomobject]@{
		SizeBytes = [int64]$fileInfo.Length
		MimeType  = Get-MimeTypeFromPath -FilePath $attachmentPath
	}
}

if (-not (Test-Path -LiteralPath $SourceDirectory -PathType Container)) {
	throw "SourceDirectory does not exist or is not a folder: $SourceDirectory"
}

Write-Stage -Group Init -Message "Starting config-driven InfoPath extraction."
Write-Stage -Group Input -Message "Source directory: $SourceDirectory"
Write-Stage -Group Input -Message "Output directory: $OutputDirectory"

# Load versioning data if provided
$versionIndex = @{}
$useVersioning = $false

if (-not [string]::IsNullOrWhiteSpace($VersioningCsvPath) -and (Test-Path -LiteralPath $VersioningCsvPath -PathType Leaf)) {
	if ([string]::IsNullOrWhiteSpace($AnalysisDirectory)) {
		throw "AnalysisDirectory is required when VersioningCsvPath is provided"
	}

	Write-Stage -Group Parse -Message "Loading versioning CSV: $VersioningCsvPath"
	
	try {
		$versionData = Import-Csv -LiteralPath $VersioningCsvPath -Encoding UTF8
		$versionIndex = New-VersionIndex -VersionRows $versionData
		$useVersioning = $true
		Write-Stage -Group Parse -Message "Loaded version mappings for $($versionIndex.Count) files"
	}
	catch {
		Write-Stage -Group Warn -Message "Could not load versioning CSV: $($_.Exception.Message)"
	}
}

# Get XML files to process first (needed for version resolution)
$searchParameters = @{
	LiteralPath = $SourceDirectory
	Filter      = "*.xml"
	File        = $true
}
if ($Recurse.IsPresent) { $searchParameters.Recurse = $true }

$xmlFiles = @(Get-ChildItem @searchParameters)

if ($xmlFiles.Count -eq 0) {
	throw "No XML files found in: $SourceDirectory"
}

Write-Stage -Group Input -Message "Discovered $($xmlFiles.Count) XML files to process"

# Load or generate structure config(s)
$structureConfigs = @{}  # Key: Version or "default", Value: config hashtable

if ($useVersioning -and $versionIndex.Count -gt 0) {
	# Version-based config loading
	Write-Stage -Group Parse -Message "Loading version-specific structure configs from: $AnalysisDirectory"
	
	$versionsFound = New-Object System.Collections.Generic.HashSet[string]
	
	# Scan files to get unique versions
	foreach ($xmlFile in $xmlFiles) {
		$fileVersion = Resolve-FileVersion -XmlFile $xmlFile -VersionIndex $versionIndex
		if (-not [string]::IsNullOrWhiteSpace($fileVersion) -and -not $versionsFound.Contains($fileVersion)) {
			$null = $versionsFound.Add($fileVersion)
		}
	}
	
	Write-Stage -Group Parse -Message "Found $($versionsFound.Count) unique versions in files"
	
	# Load structure config for each version
	foreach ($version in $versionsFound) {
		$safeName = ($version -replace "[^A-Za-z0-9_-]", "_")
		$configPath = Join-Path -Path $AnalysisDirectory -ChildPath "StructureReport_$safeName.json"
		
		if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
			Write-Stage -Group Warn -Message "Structure config not found for version '$version': $configPath"
			continue
		}
		
		Write-Stage -Group Parse -Message "Loading structure config for version '$version': $configPath"
		
		try {
			$configJson = Get-Content -Path $configPath -Raw -Encoding UTF8
			$report = $configJson | ConvertFrom-Json
			
			$structureConfigs[$version] = @{
				NonRepeatingFields = @($report.NonRepeatingFields | Select-Object -ExpandProperty XPath | ForEach-Object { @{XPath=$_} })
				RepeatingGroups    = @($report.RepeatingGroups | Select-Object -Property GroupPath, GroupName, ChildFields)
			}
			
			Write-Stage -Group Parse -Message "  Version '$version': $(@($structureConfigs[$version].NonRepeatingFields).Count) fields, $(@($structureConfigs[$version].RepeatingGroups).Count) groups"
		}
		catch {
			Write-Stage -Group Warn -Message "Failed to load structure config for version '$version': $($_.Exception.Message)"
		}
	}
	
	if ($structureConfigs.Count -eq 0) {
		throw "No version-specific structure configs could be loaded from: $AnalysisDirectory"
	}
}
else {
	# Single config or auto-analysis
	if ([string]::IsNullOrWhiteSpace($StructureConfigPath)) {
		Write-Stage -Group Parse -Message "No StructureConfigPath provided. Running auto-analysis..."
		
		# Quick inline analysis
		$sampleFiles = @($xmlFiles | Get-Random -Count ([Math]::Min(2, $xmlFiles.Count)))
		
		Write-Stage -Group Parse -Message "Analyzed $($sampleFiles.Count) sample files for structure"
		
		# Create minimal config from samples
		$allPaths = New-Object System.Collections.Generic.HashSet[string]
		foreach ($xmlFile in $sampleFiles) {
			try {
				$sr = [System.IO.StreamReader]::new($xmlFile.FullName, $true)
				$rawXml = $sr.ReadToEnd()
				$sr.Close()
				$sr.Dispose()

				$xmlSettings = [System.Xml.XmlReaderSettings]::new()
				$xmlSettings.IgnoreComments = $true
				$xmlSettings.IgnoreWhitespace = $true
				$xmlSettings.DtdProcessing = [System.Xml.DtdProcessing]::Prohibit

				$xmlDocument = [System.Xml.XmlDocument]::new()
				$xmlDocument.XmlResolver = $null
				$xr = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($rawXml), $xmlSettings)
				$xmlDocument.Load($xr)
				$xr.Dispose()

				if ($null -ne $xmlDocument.DocumentElement) {
					$fieldMap = @{}
					Add-XmlNodeValues -Node $xmlDocument.DocumentElement -Path $xmlDocument.DocumentElement.Name -Map $fieldMap
					foreach ($path in $fieldMap.Keys) {
						$null = $allPaths.Add($path)
					}
				}
			}
			catch {
				Write-Stage -Group Warn -Message "Could not analyze $($xmlFile.Name): $($_.Exception.Message)"
			}
		}
		
		# Minimal structure config - all paths are non-repeating
		$structureConfigs["default"] = @{
			NonRepeatingFields = @($allPaths | Where-Object { $_ -notlike "*[@]*" -and $_ -notlike "*[*]*" } | ForEach-Object { @{XPath=$_} })
			RepeatingGroups    = @()
		}
	}
	else {
		if (-not (Test-Path -LiteralPath $StructureConfigPath)) {
			throw "StructureConfigPath does not exist: $StructureConfigPath"
		}
		
		Write-Stage -Group Parse -Message "Loading structure config: $StructureConfigPath"
		$configJson = Get-Content -Path $StructureConfigPath -Raw -Encoding UTF8
		$report = $configJson | ConvertFrom-Json
		
		$structureConfigs["default"] = @{
			NonRepeatingFields = @($report.NonRepeatingFields | Select-Object -ExpandProperty XPath | ForEach-Object { @{XPath=$_} })
			RepeatingGroups    = @($report.RepeatingGroups | Select-Object -Property GroupPath, GroupName, ChildFields)
		}
	}
}

Write-Stage -Group Extract -Message "Loaded $($structureConfigs.Count) structure config(s)"

# Build combined config from all versions for unified output
$combinedConfig = @{
	NonRepeatingFields = @()
	RepeatingGroups    = @()
}

if ($structureConfigs.Count -gt 1 -or ($structureConfigs.Count -eq 1 -and -not $structureConfigs.ContainsKey("default"))) {
	# Multiple versions - merge all configs
	Write-Stage -Group Map -Message "Merging structure configs from $($structureConfigs.Count) versions..."
	
	$allNonRepeatingPaths = New-Object System.Collections.Generic.HashSet[string]
	$allGroupPaths = @{}
	
	foreach ($version in $structureConfigs.Keys) {
		$config = $structureConfigs[$version]
		
		foreach ($field in $config.NonRepeatingFields) {
			$null = $allNonRepeatingPaths.Add($field.XPath)
		}
		
		foreach ($group in $config.RepeatingGroups) {
			if (-not $allGroupPaths.ContainsKey($group.GroupName)) {
				$allGroupPaths[$group.GroupName] = $group
			}
		}
	}
	
	$combinedConfig.NonRepeatingFields = @($allNonRepeatingPaths | ForEach-Object { @{XPath=$_} })
	$combinedConfig.RepeatingGroups = @($allGroupPaths.Values)
}
else {
	# Single version or default - use as-is
	$singleKey = if ($structureConfigs.ContainsKey("default")) { "default" } else { @($structureConfigs.Keys | Select-Object -First 1)[0] }
	$combinedConfig = $structureConfigs[$singleKey]
}

Write-Stage -Group Map -Message "Combined config: $(@($combinedConfig.NonRepeatingFields).Count) non-repeating fields, $(@($combinedConfig.RepeatingGroups).Count) repeating groups"

# Resolve and create output directory early so files are written during processing
if (-not (Test-Path -LiteralPath $OutputDirectory -PathType Container)) {
	Write-Stage -Group Write -Message "Creating output directory: $OutputDirectory"
	New-Item -Path $OutputDirectory -ItemType Directory -Force | Out-Null
}
$outputRoot = (Resolve-Path -LiteralPath $OutputDirectory).Path
$normalizedDir = Join-Path -Path $outputRoot -ChildPath "Normalized"
if (-not (Test-Path -LiteralPath $normalizedDir -PathType Container)) {
	Write-Stage -Group Write -Message "Creating output directory: $normalizedDir"
	New-Item -Path $normalizedDir -ItemType Directory -Force | Out-Null
}

# Build column mapping
Write-Stage -Group Map -Message "Building column name mapping..."
$columnMapping = @{}
$shortToOriginal = @{}
$allColumns = New-Object System.Collections.Generic.List[string]
$allColumns.Add("SourceFilePath") | Out-Null
$allColumns.Add("SourceFileName") | Out-Null
foreach ($field in @($combinedConfig.NonRepeatingFields)) {
	if ($null -ne $field.XPath -and -not [string]::IsNullOrWhiteSpace($field.XPath)) {
		$allColumns.Add($field.XPath) | Out-Null
	}
}

foreach ($col in $allColumns) {
	$shortName = Get-AbbreviatedName -OriginalPath $col
	$shortToOriginal[$shortName] = $col
	
	$groupName = "Main"
	if ($col -like "*[@]*") {
		$groupName = "Metadata"
	}
	
	foreach ($group in $combinedConfig.RepeatingGroups) {
		if ($col -like "$($group.GroupPath)/*") {
			$groupName = $group.GroupName
			break
		}
	}
	
	$columnMapping[$shortName] = @{
		OriginalPath = $col
		Group        = $groupName
	}
}

Write-Stage -Group Map -Message "Created $($columnMapping.Count) column mappings"

# Prepare output files for streaming writes
$mainCsvPath = Join-Path -Path $normalizedDir -ChildPath "Main.csv"
if (Test-Path -LiteralPath $mainCsvPath -PathType Leaf) {
	Remove-Item -LiteralPath $mainCsvPath -Force
}

$groupCsvPaths = @{}
$groupRowCounts = @{}
foreach ($group in @($combinedConfig.RepeatingGroups)) {
	$safeGroupName = (($group.GroupName -replace "[^A-Za-z0-9_-]", "_").Trim('_'))
	if ([string]::IsNullOrWhiteSpace($safeGroupName)) {
		$safeGroupName = "Group"
	}
	$groupCsvPath = Join-Path -Path $normalizedDir -ChildPath ("{0}.csv" -f $safeGroupName)
	if (Test-Path -LiteralPath $groupCsvPath -PathType Leaf) {
		Remove-Item -LiteralPath $groupCsvPath -Force
	}
	$groupCsvPaths[$group.GroupName] = $groupCsvPath
	$groupRowCounts[$group.GroupName] = 0
}

$processedCount = 0

# Extract data and append as each file is processed
foreach ($xmlFile in $xmlFiles) {
	Write-Stage -Group Parse -Message "Extracting: $($xmlFile.Name)"
	
	try {
		# Determine which structure config to use for this file
		$fileVersion = if ($useVersioning) { Resolve-FileVersion -XmlFile $xmlFile -VersionIndex $versionIndex } else { "default" }
		$activeConfig = if ($fileVersion -and $structureConfigs.ContainsKey($fileVersion)) { $structureConfigs[$fileVersion] } else { $structureConfigs["default"] }
		
		if ($null -eq $activeConfig) {
			Write-Stage -Group Warn -Message "No structure config available for file version '$fileVersion'. Skipping: $($xmlFile.Name)"
			continue
		}
		
		Write-Stage -Group Parse -Message "  Using structure config for version: '$fileVersion'"
		
		$sr = [System.IO.StreamReader]::new($xmlFile.FullName, $true)
		$rawXml = $sr.ReadToEnd()
		$sr.Close()
		$sr.Dispose()

		$xmlSettings = [System.Xml.XmlReaderSettings]::new()
		$xmlSettings.IgnoreComments = $true
		$xmlSettings.IgnoreWhitespace = $true
		$xmlSettings.DtdProcessing = [System.Xml.DtdProcessing]::Prohibit

		$xmlDocument = [System.Xml.XmlDocument]::new()
		$xmlDocument.XmlResolver = $null
		$xr = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($rawXml), $xmlSettings)
		try {
			$xmlDocument.Load($xr)
		}
		finally {
			$xr.Dispose()
		}

		if ($null -ne $xmlDocument.DocumentElement) {
			$relativeXmlPath = Get-RelativePath -BasePath $SourceDirectory -FullPath $xmlFile.FullName
			$relativeXmlStem = [System.IO.Path]::ChangeExtension($relativeXmlPath, $null)
			$attachmentFolderName = "{0}_attachments" -f (Convert-ToSafeFileName -Value ($relativeXmlStem -replace '[\\/]+', '_'))
			$attachmentOutputDirectory = Join-Path -Path $normalizedDir -ChildPath $attachmentFolderName
			if (-not (Test-Path -LiteralPath $attachmentOutputDirectory -PathType Container)) {
				New-Item -Path $attachmentOutputDirectory -ItemType Directory -Force | Out-Null
			}

			$attachmentCount = Expand-EmbeddedAttachments -Node $xmlDocument.DocumentElement -AttachmentOutputDirectory $attachmentOutputDirectory -RelativePrefix $attachmentFolderName
			if ($attachmentCount -gt 0) {
				Write-Stage -Group Extract -Message "  Extracted $attachmentCount embedded attachment(s)"
			}

			$fieldMap = @{}
			Add-XmlNodeValues -Node $xmlDocument.DocumentElement -Path $xmlDocument.DocumentElement.Name -Map $fieldMap

			$mainRow = [ordered]@{
				SourceFilePath = $xmlFile.FullName
				SourceFileName = $xmlFile.Name
			}

			foreach ($col in $allColumns) {
				if ($col -eq "SourceFilePath" -or $col -eq "SourceFileName") {
					continue
				}
				$shortName = Get-AbbreviatedName -OriginalPath $col
				$mapping = $columnMapping[$shortName]
				if ($mapping.Group -eq "Main") {
					$value = $null
					if ($fieldMap.ContainsKey($col)) {
						$value = [string]$fieldMap[$col]
					}
					$mainRow[$shortName] = $value
					$mainRow["${shortName}_AttachSizeBytes"] = $null
					$mainRow["${shortName}_AttachMimeType"] = $null

					$attachmentMeta = Resolve-AttachmentMetadata -Value $value -AttachmentBaseDirectory $normalizedDir
					if ($null -ne $attachmentMeta) {
						$mainRow["${shortName}_AttachSizeBytes"] = $attachmentMeta.SizeBytes
						$mainRow["${shortName}_AttachMimeType"] = $attachmentMeta.MimeType
					}
				}
			}

			$mainObj = [pscustomobject]$mainRow
			if ($processedCount -eq 0) {
				$mainObj | Export-Csv -Path $mainCsvPath -NoTypeInformation -Encoding UTF8
			}
			else {
				$mainObj | Export-Csv -Path $mainCsvPath -NoTypeInformation -Encoding UTF8 -Append -Force
			}

			$processedCount++
			Write-Stage -Group Write -Message "  Appended row $processedCount to Main.csv"

			# Stream repeating group rows to one CSV per group
			foreach ($group in @($combinedConfig.RepeatingGroups)) {
				$groupPath = $group.GroupPath
				if ([string]::IsNullOrWhiteSpace($groupPath)) {
					continue
				}

				$escapedGroupPath = [regex]::Escape($groupPath)
				$pattern = "^{0}\[(\d+)\]/(.+)$" -f $escapedGroupPath
				$rowsBySequence = @{}

				foreach ($key in $fieldMap.Keys) {
					$match = [regex]::Match($key, $pattern)
					if (-not $match.Success) {
						continue
					}

					$sequence = $match.Groups[1].Value
					$relativePath = $match.Groups[2].Value
					$relativePath = $relativePath -replace "\[\d+\]", ""
					$columnName = Get-AbbreviatedName -OriginalPath $relativePath

					if (-not $rowsBySequence.ContainsKey($sequence)) {
						$rowsBySequence[$sequence] = [ordered]@{
							SourceFilePath = $xmlFile.FullName
							SourceFileName = $xmlFile.Name
							Version        = $fileVersion
							SequenceNumber = [int]$sequence
						}
					}

					$rowsBySequence[$sequence][$columnName] = $fieldMap[$key]
					$rowsBySequence[$sequence]["${columnName}_AttachSizeBytes"] = $null
					$rowsBySequence[$sequence]["${columnName}_AttachMimeType"] = $null

					$attachmentMeta = Resolve-AttachmentMetadata -Value ([string]$fieldMap[$key]) -AttachmentBaseDirectory $normalizedDir
					if ($null -ne $attachmentMeta) {
						$rowsBySequence[$sequence]["${columnName}_AttachSizeBytes"] = $attachmentMeta.SizeBytes
						$rowsBySequence[$sequence]["${columnName}_AttachMimeType"] = $attachmentMeta.MimeType
					}
				}

				if ($rowsBySequence.Count -eq 0) {
					continue
				}

				$groupCsvPath = $groupCsvPaths[$group.GroupName]
				foreach ($sequence in @($rowsBySequence.Keys | Sort-Object {[int]$_})) {
					$groupObj = [pscustomobject]$rowsBySequence[$sequence]
					if ($groupRowCounts[$group.GroupName] -eq 0) {
						$groupObj | Export-Csv -Path $groupCsvPath -NoTypeInformation -Encoding UTF8
					}
					else {
						$groupObj | Export-Csv -Path $groupCsvPath -NoTypeInformation -Encoding UTF8 -Append -Force
					}
					$groupRowCounts[$group.GroupName]++
				}
				Write-Stage -Group Write -Message "  Appended $($rowsBySequence.Count) row(s) to $($group.GroupName).csv"
			}
		}
	}
	catch {
		Write-Stage -Group Warn -Message "Skipping $($xmlFile.Name): $($_.Exception.Message)"
	}
}

if ($processedCount -eq 0) {
	throw "No valid XML files were extracted from: $SourceDirectory"
}

# Write PropertyMapping CSV
Write-Stage -Group Write -Message "Writing PropertyMapping.csv"
$mappingCsvPath = Join-Path -Path $normalizedDir -ChildPath "PropertyMapping.csv"
$mappingRows = New-Object System.Collections.Generic.List[object]

foreach ($shortName in ($columnMapping.Keys | Sort-Object)) {
	$mapping = $columnMapping[$shortName]
	$mappingRows.Add([pscustomobject]@{
		ShortName                  = $shortName
		OriginalXPath              = $mapping.OriginalPath
		TableName                  = $mapping.Group
		HasAttachmentMetadata      = 'Yes'
		AttachSizeBytesColumnName  = "${shortName}_AttachSizeBytes"
		AttachMimeTypeColumnName   = "${shortName}_AttachMimeType"
	})
}

$mappingRows | Export-Csv -Path $mappingCsvPath -NoTypeInformation -Encoding UTF8
Write-Stage -Group Write -Message "  Wrote $($mappingRows.Count) mappings"

Write-Stage -Group Done -Message "Extraction complete."
Write-Stage -Group Done -Message "  XML files processed: $processedCount"
Write-Stage -Group Done -Message "  Output directory: $normalizedDir"
Write-Stage -Group Done -Message "  Main rows: $processedCount"
foreach ($groupName in @($groupRowCounts.Keys | Sort-Object)) {
	Write-Stage -Group Done -Message "  $groupName rows: $($groupRowCounts[$groupName])"
}
Write-Stage -Group Done -Message "  CSV files: Main.csv, PropertyMapping.csv, plus one file per repeating group"
