<#
.SYNOPSIS
	Transforms InfoPath XML files into HTML, optionally PDF, using group-specific XSLT templates.

.DESCRIPTION
	Processes InfoPath XML files from a source directory and transforms each file to HTML using
	the XSLT template resolved from the grouping CSV and template-mapping CSV produced by the
	newer InfoPath analysis pipeline. Optionally prints the generated HTML to PDF using Edge or Chrome.

.PARAMETER InfoPathDirectory
	Root folder containing InfoPath XML files to process.

.PARAMETER MetadataCsvPath
	Path to the metadata CSV used to inject metadata values into XSLT parameters.

.PARAMETER GroupingCsvPath
	Path to the detailed grouping CSV generated by AnalyzeInfoPathGroupingFromCsv.ps1.
	This file is used to resolve SuggestedGroup for each InfoPath XML file.

.PARAMETER TemplateMappingCsvPath
	Path to the template mapping CSV generated by BuildXsltFromGroupingCsv.ps1.
	This file maps SuggestedGroup to the correct XSLT/CSS assets.

.PARAMETER OutputDirectory
	Destination root folder for generated HTML files and copied CSS assets.

.PARAMETER PrintToPdf
	String true/false style parameter controlling PDF generation.
	Accepted values: yes, no, true, false, 1, 0.
	Default: false

.PARAMETER ErrorLogPath
	Optional path for the processing error log file.
	If omitted, a default log file is created in the output directory.

.PARAMETER FailedFilesDirectory
	Optional folder where failed XML files are copied for review.
	If omitted, a default folder is created under the output directory.

.PARAMETER Recurse
	Include subfolders when discovering XML files to process.

.EXAMPLE
	.\ProcessInfopathToHTML.ps1 `
	  -InfoPathDirectory "C:\Temp\RedApps" `
	  -MetadataCsvPath "C:\Temp\Reports\InfoPathVersionMap.csv" `
	  -GroupingCsvPath "C:\Temp\Reports\InfoPathGroupingDetailed.csv" `
	  -TemplateMappingCsvPath "C:\Temp\Templates\InfoPathXsltGroupMap.csv" `
	  -OutputDirectory "C:\Temp\HtmlOutput" `
	  -Recurse

.EXAMPLE
	.\ProcessInfopathToHTML.ps1 `
	  -InfoPathDirectory "C:\Temp\RedApps" `
	  -MetadataCsvPath "C:\Temp\Reports\InfoPathVersionMap.csv" `
	  -GroupingCsvPath "C:\Temp\Reports\InfoPathGroupingDetailed.csv" `
	  -TemplateMappingCsvPath "C:\Temp\Templates\InfoPathXsltGroupMap.csv" `
	  -OutputDirectory "C:\Temp\HtmlOutput" `
	  -PrintToPdf "true"

.NOTES
	Requires the prior pipeline outputs from:
	- ClassifyInfoPathVersions.ps1
	- AnalyzeInfoPathGroupingFromCsv.ps1
	- BuildXsltFromGroupingCsv.ps1
#>

[CmdletBinding()]
param(
	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$InfoPathDirectory,

	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$MetadataCsvPath,

	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$GroupingCsvPath,

	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$TemplateMappingCsvPath,

	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string]$OutputDirectory,

	[Parameter()]
	[string]$PrintToPdf = "false",

	[Parameter()]
	[string]$ErrorLogPath,

	[Parameter()]
	[string]$FailedFilesDirectory,

	[switch]$Recurse
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Stage {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Message,

		[ValidateSet("Init", "Input", "Resolve", "Build", "Write", "Pdf", "Done", "Warn", "Error")]
		[string]$Group = "Build"
	)

	$color = switch ($Group) {
		"Init" { "Cyan" }
		"Input" { "DarkCyan" }
		"Resolve" { "Yellow" }
		"Build" { "White" }
		"Write" { "Green" }
		"Pdf" { "Magenta" }
		"Done" { "Blue" }
		"Warn" { "DarkYellow" }
		"Error" { "Red" }
		default { "White" }
	}

	Write-Host "[$Group] $Message" -ForegroundColor $color
}

function Convert-ToBooleanValue {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Value,

		[string]$ParameterName = "PrintToPdf"
	)

	$normalized = $Value.Trim().ToLowerInvariant()
	switch ($normalized) {
		"1" { return $true }
		"0" { return $false }
		"true" { return $true }
		"false" { return $false }
		"yes" { return $true }
		"no" { return $false }
		default {
			throw "$ParameterName must be one of: yes, no, true, false, 1, 0"
		}
	}
}

function Get-RelativePath {
	param(
		[Parameter(Mandatory = $true)]
		[string]$BasePath,
		[Parameter(Mandatory = $true)]
		[string]$FullPath
	)

	# Normalize paths to absolute form
	$basePath = [System.IO.Path]::GetFullPath($BasePath).TrimEnd(
		[System.IO.Path]::DirectorySeparatorChar,
		[System.IO.Path]::AltDirectorySeparatorChar
	)
	$fullPath = [System.IO.Path]::GetFullPath($FullPath)

	# Use Uri to calculate relative path (compatible with .NET Framework)
	try {
		$baseUri = New-Object Uri($basePath + [System.IO.Path]::DirectorySeparatorChar)
		$fullUri = New-Object Uri($fullPath)
		$relativeUri = $baseUri.MakeRelativeUri($fullUri)
		$relativePath = [System.Uri]::UnescapeDataString($relativeUri.ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
		return $relativePath
	}
	catch {
		# Fallback for edge cases
		return $fullPath
	}
}

function Convert-ToXsltParamName {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Name
	)

	$sanitized = ($Name -replace "[^A-Za-z0-9_]", "_")
	if ($sanitized -match "^[0-9]") {
		$sanitized = "_$sanitized"
	}

	return "meta_$sanitized"
}

function Find-PdfBrowser {
	$candidates = @(
		"$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe",
		"${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
		"$env:LOCALAPPDATA\Microsoft\Edge\Application\msedge.exe",
		"$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
		"${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
		"$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
	)

	foreach ($candidate in $candidates) {
		if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
			return $candidate
		}
	}

	return $null
}

function New-MetadataIndex {
	param(
		[Parameter(Mandatory = $true)]
		[object[]]$Rows
	)

	$index = @{}

	foreach ($row in $Rows) {
		$props = $row.PSObject.Properties.Name

		foreach ($fullPathColumn in @("SourceFilePath", "FilePath", "Path", "FullName")) {
			if ($props -contains $fullPathColumn) {
				$fullPath = [string]$row.$fullPathColumn
				if (-not [string]::IsNullOrWhiteSpace($fullPath)) {
					$key = "FULL::$($fullPath.ToLowerInvariant())"
					if (-not $index.ContainsKey($key)) {
						$index[$key] = $row
					}
				}
			}
		}

		foreach ($nameColumn in @("FileName", "SourceFileName", "FileLeafRef", "Name")) {
			if ($props -contains $nameColumn) {
				$nameValue = [string]$row.$nameColumn
				if (-not [string]::IsNullOrWhiteSpace($nameValue)) {
					$key = "NAME::$($nameValue.ToLowerInvariant())"
					if (-not $index.ContainsKey($key)) {
						$index[$key] = $row
					}
				}
			}
		}
	}

	return $index
}

function Resolve-MetadataRow {
	param(
		[Parameter(Mandatory = $true)]
		[System.IO.FileInfo]$XmlFile,

		[Parameter(Mandatory = $true)]
		[hashtable]$MetadataIndex
	)

	$fullPathKey = "FULL::$($XmlFile.FullName.ToLowerInvariant())"
	if ($MetadataIndex.ContainsKey($fullPathKey)) {
		return $MetadataIndex[$fullPathKey]
	}

	$nameKey = "NAME::$($XmlFile.Name.ToLowerInvariant())"
	if ($MetadataIndex.ContainsKey($nameKey)) {
		return $MetadataIndex[$nameKey]
	}

	return $null
}

function New-FileRowIndex {
	param(
		[Parameter(Mandatory = $true)]
		[object[]]$Rows
	)

	$index = @{}

	foreach ($row in $Rows) {
		$props = $row.PSObject.Properties.Name

		foreach ($fullPathColumn in @("SourceFilePath", "FilePath", "Path", "FullName")) {
			if ($props -contains $fullPathColumn) {
				$fullPath = [string]$row.$fullPathColumn
				if (-not [string]::IsNullOrWhiteSpace($fullPath)) {
					$key = "FULL::$($fullPath.ToLowerInvariant())"
					if (-not $index.ContainsKey($key)) {
						$index[$key] = $row
					}
				}
			}
		}

		foreach ($nameColumn in @("SourceFileName", "FileName", "Name", "FileLeafRef")) {
			if ($props -contains $nameColumn) {
				$nameValue = [string]$row.$nameColumn
				if (-not [string]::IsNullOrWhiteSpace($nameValue)) {
					$key = "NAME::$($nameValue.ToLowerInvariant())"
					if (-not $index.ContainsKey($key)) {
						$index[$key] = $row
					}
				}
			}
		}
	}

	return $index
}

function Resolve-IndexedFileRow {
	param(
		[Parameter(Mandatory = $true)]
		[System.IO.FileInfo]$XmlFile,
		[Parameter(Mandatory = $true)]
		[hashtable]$Index
	)

	$fullPathKey = "FULL::$($XmlFile.FullName.ToLowerInvariant())"
	if ($Index.ContainsKey($fullPathKey)) {
		return $Index[$fullPathKey]
	}

	$nameKey = "NAME::$($XmlFile.Name.ToLowerInvariant())"
	if ($Index.ContainsKey($nameKey)) {
		return $Index[$nameKey]
	}

	return $null
}

function New-TemplateMappingIndex {
	param(
		[Parameter(Mandatory = $true)]
		[object[]]$Rows
	)

	$index = @{}
	foreach ($row in $Rows) {
		$suggestedGroup = [string]$row.SuggestedGroup
		if ([string]::IsNullOrWhiteSpace($suggestedGroup)) {
			continue
		}

		$key = $suggestedGroup.ToLowerInvariant()
		if (-not $index.ContainsKey($key)) {
			$index[$key] = $row
		}
	}

	return $index
}

function Get-XsltTransformFromCache {
	param(
		[Parameter(Mandatory = $true)]
		[string]$XsltPath,
		[Parameter(Mandatory = $true)]
		[hashtable]$Cache
	)

	$key = $XsltPath.ToLowerInvariant()
	if (-not $Cache.ContainsKey($key)) {
		$transform = New-Object System.Xml.Xsl.XslCompiledTransform
		$transform.Load($XsltPath)
		$Cache[$key] = $transform
	}

	return $Cache[$key]
}

function Write-ErrorLogEntry {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyCollection()]
		[System.Collections.Generic.List[string]]$ErrorLogEntries,
		[Parameter(Mandatory = $true)]
		[string]$SourceFile,
		[Parameter(Mandatory = $true)]
		[string]$Message
	)

	$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
	$ErrorLogEntries.Add("[$timestamp] File='$SourceFile' Error='$Message'") | Out-Null
}

function Copy-FailedInfoPathFile {
	param(
		[Parameter(Mandatory = $true)]
		[System.IO.FileInfo]$XmlFile,
		[Parameter(Mandatory = $true)]
		[string]$SourceRoot,
		[Parameter(Mandatory = $true)]
		[string]$FailureRoot
	)

	$relativePath = Get-RelativePath -BasePath $SourceRoot -FullPath $XmlFile.FullName
	$targetPath = Join-Path -Path $FailureRoot -ChildPath $relativePath
	$targetDirectory = Split-Path -Path $targetPath -Parent

	if (-not [string]::IsNullOrWhiteSpace($targetDirectory) -and -not (Test-Path -LiteralPath $targetDirectory -PathType Container)) {
		New-Item -Path $targetDirectory -ItemType Directory -Force | Out-Null
	}

	Copy-Item -LiteralPath $XmlFile.FullName -Destination $targetPath -Force
	return $targetPath
}

function Convert-ToSafeFileName {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Value
	)

	$safe = $Value
	foreach ($invalid in [System.IO.Path]::GetInvalidFileNameChars()) {
		$safe = $safe.Replace($invalid, '_')
	}

	$safe = ($safe -replace '[\s]+', '_').Trim('_')
	if ([string]::IsNullOrWhiteSpace($safe)) {
		return 'attachment'
	}

	return $safe
}

function Get-NodeChildElements {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node
	)

	return ,@($Node.ChildNodes | Where-Object { $_.NodeType -eq [System.Xml.XmlNodeType]::Element })
}

function Try-DecodeInfoPathAttachment {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyString()]
		[string]$Value
	)

	if ([string]::IsNullOrWhiteSpace($Value)) {
		return $null
	}

	$candidate = $Value.Trim()
	if ($candidate.Length -lt 64 -or ($candidate -notmatch '^[A-Za-z0-9+/=\r\n]+$')) {
		return $null
	}

	try {
		$bytes = [System.Convert]::FromBase64String($candidate)
	}
	catch {
		return $null
	}

	if ($bytes.Length -lt 28) {
		return $null
	}

	if ($bytes[0] -ne 0xC7 -or $bytes[1] -ne 0x49 -or $bytes[2] -ne 0x46 -or $bytes[3] -ne 0x41) {
		return $null
	}

	$stream = [System.IO.MemoryStream]::new($bytes)
	$reader = [System.IO.BinaryReader]::new($stream)

	try {
		$null = $reader.ReadBytes(16)
		$fileSize = $reader.ReadUInt32()
		$fileNameCharacterCount = $reader.ReadUInt32()

		if ($fileNameCharacterCount -lt 1 -or $fileNameCharacterCount -gt [int]::MaxValue / 2) {
			return $null
		}

		$fileNameByteLength = [int]$fileNameCharacterCount * 2
		if ($fileNameByteLength -gt ($bytes.Length - 24)) {
			return $null
		}

		$fileNameBytes = $reader.ReadBytes($fileNameByteLength)
		if ($fileNameBytes.Length -lt $fileNameByteLength) {
			return $null
		}

		$decodedName = [System.Text.Encoding]::Unicode.GetString($fileNameBytes)
		$decodedName = $decodedName.Trim([char]0)
		if ([string]::IsNullOrWhiteSpace($decodedName)) {
			$decodedName = 'attachment.bin'
		}

		$remaining = [int]($stream.Length - $stream.Position)
		if ($remaining -le 0) {
			return $null
		}

		$bytesToRead = [Math]::Min([int]$fileSize, $remaining)
		if ($bytesToRead -le 0) {
			$bytesToRead = $remaining
		}

		$fileBytes = $reader.ReadBytes($bytesToRead)
		if ($fileBytes.Length -eq 0) {
			return $null
		}

		return @{
			FileName = [System.IO.Path]::GetFileName($decodedName)
			Content  = $fileBytes
		}
	}
	catch {
		return $null
	}
	finally {
		$reader.Dispose()
		$stream.Dispose()
	}
}

function New-UniqueAttachmentPath {
	param(
		[Parameter(Mandatory = $true)]
		[string]$DirectoryPath,
		[Parameter(Mandatory = $true)]
		[string]$DesiredName
	)

	$baseName = [System.IO.Path]::GetFileNameWithoutExtension($DesiredName)
	$extension = [System.IO.Path]::GetExtension($DesiredName)
	if ([string]::IsNullOrWhiteSpace($extension)) {
		$extension = '.bin'
	}

	$safeBase = Convert-ToSafeFileName -Value $baseName
	$candidate = Join-Path -Path $DirectoryPath -ChildPath ($safeBase + $extension)
	$counter = 1

	while (Test-Path -LiteralPath $candidate -PathType Leaf) {
		$candidate = Join-Path -Path $DirectoryPath -ChildPath ("{0}_{1}{2}" -f $safeBase, $counter, $extension)
		$counter++
	}

	return $candidate
}

function Expand-EmbeddedAttachments {
	param(
		[Parameter(Mandatory = $true)]
		[System.Xml.XmlNode]$Node,
		[Parameter(Mandatory = $true)]
		[string]$CurrentPath,
		[Parameter(Mandatory = $true)]
		[string]$AttachmentOutputDirectory,
		[Parameter(Mandatory = $true)]
		[string]$RelativePrefix
	)

	$extractedCount = 0

	$children = Get-NodeChildElements -Node $Node
	if ($children.Count -eq 0) {
		$decodedAttachment = Try-DecodeInfoPathAttachment -Value $Node.InnerText
		if ($null -eq $decodedAttachment) {
			return 0
		}

		$desiredName = if ([string]::IsNullOrWhiteSpace($decodedAttachment.FileName)) { 'attachment.bin' } else { $decodedAttachment.FileName }
		$targetFilePath = New-UniqueAttachmentPath -DirectoryPath $AttachmentOutputDirectory -DesiredName $desiredName
		[System.IO.File]::WriteAllBytes($targetFilePath, $decodedAttachment.Content)

		$fileName = [System.IO.Path]::GetFileName($targetFilePath)
		$relativePath = "{0}/{1}" -f $RelativePrefix.TrimEnd('/'), $fileName
		$Node.InnerText = "ATTACHMENT::$relativePath"
		return 1
	}

	$nameCounts = @{}
	foreach ($child in $children) {
		if ($nameCounts.ContainsKey($child.Name)) {
			$nameCounts[$child.Name]++
		}
		else {
			$nameCounts[$child.Name] = 1
		}
	}

	$nameIndexes = @{}
	foreach ($child in $children) {
		if ($nameIndexes.ContainsKey($child.Name)) {
			$nameIndexes[$child.Name]++
		}
		else {
			$nameIndexes[$child.Name] = 1
		}

		$childPath = "$CurrentPath/$($child.Name)"
		if ($nameCounts[$child.Name] -gt 1) {
			$childPath = "$childPath[$($nameIndexes[$child.Name])]"
		}

		$extractedCount += Expand-EmbeddedAttachments -Node $child -CurrentPath $childPath -AttachmentOutputDirectory $AttachmentOutputDirectory -RelativePrefix $RelativePrefix
	}

	return $extractedCount
}

if (-not (Test-Path -LiteralPath $InfoPathDirectory -PathType Container)) {
	throw "InfoPathDirectory does not exist or is not a folder: $InfoPathDirectory"
}

Write-Stage -Group Init -Message "Starting InfoPath to HTML processing."
Write-Stage -Group Input -Message "InfoPath directory: $InfoPathDirectory"
Write-Stage -Group Input -Message "Metadata CSV: $MetadataCsvPath"
Write-Stage -Group Input -Message "Grouping CSV: $GroupingCsvPath"
Write-Stage -Group Input -Message "Template mapping CSV: $TemplateMappingCsvPath"
Write-Stage -Group Input -Message "Output directory: $OutputDirectory"

if (-not (Test-Path -LiteralPath $MetadataCsvPath -PathType Leaf)) {
	throw "MetadataCsvPath does not exist: $MetadataCsvPath"
}

if (-not (Test-Path -LiteralPath $GroupingCsvPath -PathType Leaf)) {
	throw "GroupingCsvPath does not exist: $GroupingCsvPath"
}

if (-not (Test-Path -LiteralPath $TemplateMappingCsvPath -PathType Leaf)) {
	throw "TemplateMappingCsvPath does not exist: $TemplateMappingCsvPath"
}

if (-not (Test-Path -LiteralPath $OutputDirectory -PathType Container)) {
	New-Item -Path $OutputDirectory -ItemType Directory -Force | Out-Null
}

if ([string]::IsNullOrWhiteSpace($ErrorLogPath)) {
	$ErrorLogPath = Join-Path -Path $OutputDirectory -ChildPath "ProcessInfopathToHTML-errors.log"
}

if ([string]::IsNullOrWhiteSpace($FailedFilesDirectory)) {
	$FailedFilesDirectory = Join-Path -Path $OutputDirectory -ChildPath "FailedInfoPathFiles"
}

if (-not (Test-Path -LiteralPath $FailedFilesDirectory -PathType Container)) {
	New-Item -Path $FailedFilesDirectory -ItemType Directory -Force | Out-Null
}

$errorLogDirectory = Split-Path -Path $ErrorLogPath -Parent
if (-not [string]::IsNullOrWhiteSpace($errorLogDirectory) -and -not (Test-Path -LiteralPath $errorLogDirectory -PathType Container)) {
	New-Item -Path $errorLogDirectory -ItemType Directory -Force | Out-Null
}

$shouldPrintPdf = Convert-ToBooleanValue -Value $PrintToPdf -ParameterName "PrintToPdf"
$pdfBrowser = $null
if ($shouldPrintPdf) {
	$pdfBrowser = Find-PdfBrowser
	if ($null -eq $pdfBrowser) {
		throw "PrintToPdf was enabled, but no supported browser was found (Microsoft Edge or Google Chrome)."
	}
}

$metadataRows = @(Import-Csv -LiteralPath $MetadataCsvPath)
$metadataIndex = New-MetadataIndex -Rows $metadataRows
$groupingRows = @(Import-Csv -LiteralPath $GroupingCsvPath)
$groupingIndex = New-FileRowIndex -Rows $groupingRows
$templateMappingRows = @(Import-Csv -LiteralPath $TemplateMappingCsvPath)
$templateMappingIndex = New-TemplateMappingIndex -Rows $templateMappingRows
$xsltCache = @{}

Write-Stage -Group Input -Message "Loaded metadata rows: $($metadataRows.Count)"
Write-Stage -Group Input -Message "Loaded grouping rows: $($groupingRows.Count)"
Write-Stage -Group Input -Message "Loaded template mapping rows: $($templateMappingRows.Count)"

# Diagnostic: Show which SuggestedGroups are available in the template mapping
Write-Stage -Group Input -Message "Available SuggestedGroups in template mapping:"
foreach ($suggestedGroup in @($templateMappingIndex.Keys | Sort-Object)) {
	$row = $templateMappingIndex[$suggestedGroup]
	$xsltPath = [string]$row.XsltPath
	$fileExists = if ([string]::IsNullOrWhiteSpace($xsltPath)) { "EMPTY" } elseif (Test-Path -LiteralPath $xsltPath -PathType Leaf) { "EXISTS" } else { "MISSING" }
	Write-Stage -Group Input -Message "  - Group: $suggestedGroup | XsltPath: $xsltPath | Status: $fileExists"
}

$searchParameters = @{
	LiteralPath = $InfoPathDirectory
	Filter      = "*.xml"
	File        = $true
}

if ($Recurse.IsPresent) {
	$searchParameters.Recurse = $true
}

$xmlFiles = @(Get-ChildItem @searchParameters)
if ($xmlFiles.Count -eq 0) {
	throw "No XML files were found in: $InfoPathDirectory"
}

Write-Stage -Group Input -Message "Discovered XML files: $($xmlFiles.Count)"

$processedCount = 0
$pdfCount = 0
$failedCount = 0
$errorLogEntries = New-Object System.Collections.Generic.List[string]

foreach ($xmlFile in $xmlFiles) {
	try {
		Write-Stage -Group Build -Message "Processing file: $($xmlFile.FullName)"

		$relativePath = Get-RelativePath -BasePath $InfoPathDirectory -FullPath $xmlFile.FullName
		$relativeDirectory = Split-Path -Path $relativePath -Parent

		$destinationDirectory = if ([string]::IsNullOrWhiteSpace($relativeDirectory)) {
			$OutputDirectory
		}
		else {
			Join-Path -Path $OutputDirectory -ChildPath $relativeDirectory
		}

		if (-not (Test-Path -LiteralPath $destinationDirectory -PathType Container)) {
			New-Item -Path $destinationDirectory -ItemType Directory -Force | Out-Null
		}

		$baseName = [System.IO.Path]::GetFileNameWithoutExtension($xmlFile.Name)
		$htmlOutputPath = Join-Path -Path $destinationDirectory -ChildPath "$baseName.html"
		$pdfOutputPath = Join-Path -Path $destinationDirectory -ChildPath "$baseName.pdf"
		$attachmentDirectoryName = "{0}_attachments" -f (Convert-ToSafeFileName -Value $baseName)
		$attachmentOutputDirectory = Join-Path -Path $destinationDirectory -ChildPath $attachmentDirectoryName
		if (-not (Test-Path -LiteralPath $attachmentOutputDirectory -PathType Container)) {
			New-Item -Path $attachmentOutputDirectory -ItemType Directory -Force | Out-Null
		}

		$metadataRow = Resolve-MetadataRow -XmlFile $xmlFile -MetadataIndex $metadataIndex
		$groupingRow = Resolve-IndexedFileRow -XmlFile $xmlFile -Index $groupingIndex
		if ($null -eq $groupingRow) {
			throw "No grouping row was found for '$($xmlFile.FullName)'."
		}

		$suggestedGroup = [string]$groupingRow.SuggestedGroup
		Write-Stage -Group Resolve -Message "Resolved SuggestedGroup '$suggestedGroup' for file '$($xmlFile.Name)'."
		if ([string]::IsNullOrWhiteSpace($suggestedGroup) -or $suggestedGroup -eq 'ParseFailed') {
			throw "File '$($xmlFile.FullName)' does not have a usable SuggestedGroup."
		}

		$templateMapKey = $suggestedGroup.ToLowerInvariant()
		if (-not $templateMappingIndex.ContainsKey($templateMapKey)) {
			throw "No template mapping row was found for SuggestedGroup '$suggestedGroup'."
		}

		$templateMapRow = $templateMappingIndex[$templateMapKey]
		$resolvedXsltPath = [string]$templateMapRow.XsltPath
		Write-Stage -Group Resolve -Message "Resolving XSLT for group '$suggestedGroup': XsltPath='$resolvedXsltPath'"
		if ([string]::IsNullOrWhiteSpace($resolvedXsltPath)) {
			throw "Mapped XSLT path is EMPTY (null/blank) for SuggestedGroup '$suggestedGroup'."
		}
		if (-not (Test-Path -LiteralPath $resolvedXsltPath -PathType Leaf)) {
			$parentDir = Split-Path -Path $resolvedXsltPath -Parent
			$exists = Test-Path -LiteralPath $parentDir -PathType Container
			throw "XSLT file does not exist: '$resolvedXsltPath' (parent dir exists: $exists). Check that BuildXsltFromGroupingCsv.ps1 successfully generated the template."
		}
		Write-Stage -Group Resolve -Message "Using XSLT '$resolvedXsltPath'."

		$resolvedCssPath = [string]$templateMapRow.CssPath
		if (-not [string]::IsNullOrWhiteSpace($resolvedCssPath) -and (Test-Path -LiteralPath $resolvedCssPath -PathType Leaf)) {
			$destinationCssPath = Join-Path -Path $destinationDirectory -ChildPath ([System.IO.Path]::GetFileName($resolvedCssPath))
			if (-not (Test-Path -LiteralPath $destinationCssPath -PathType Leaf)) {
				Write-Stage -Group Write -Message "Copying CSS to '$destinationCssPath'."
				Copy-Item -LiteralPath $resolvedCssPath -Destination $destinationCssPath -Force
			}
		}

		$xslt = Get-XsltTransformFromCache -XsltPath $resolvedXsltPath -Cache $xsltCache

		$xsltArgs = New-Object System.Xml.Xsl.XsltArgumentList
		$xsltArgs.AddParam("sourceFilePath", "", $xmlFile.FullName)
		$xsltArgs.AddParam("sourceFileName", "", $xmlFile.Name)
		$xsltArgs.AddParam("templateGroup", "", $suggestedGroup)

		if ($null -ne $metadataRow) {
			foreach ($property in $metadataRow.PSObject.Properties) {
				if ([string]::IsNullOrWhiteSpace($property.Name)) {
					continue
				}

				$value = [string]$property.Value
				if ([string]::IsNullOrWhiteSpace($value)) {
					continue
				}

				$paramName = Convert-ToXsltParamName -Name $property.Name
				$xsltArgs.AddParam($paramName, "", $value)
			}
		}

		# Load into XmlDocument first so embedded attachment payloads can be decoded and replaced with file references.
		$xmlSettings = [System.Xml.XmlReaderSettings]::new()
		$xmlSettings.IgnoreComments = $true
		$xmlSettings.IgnoreWhitespace = $true
		$xmlSettings.DtdProcessing = [System.Xml.DtdProcessing]::Prohibit
		$xmlDocument = [System.Xml.XmlDocument]::new()
		$xmlDocument.XmlResolver = $null
		$streamReader = [System.IO.StreamReader]::new($xmlFile.FullName, $true)
		$rawXml = $streamReader.ReadToEnd()
		$streamReader.Dispose()
		$xmlReaderForLoad = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($rawXml), $xmlSettings)

		try {
			$xmlDocument.Load($xmlReaderForLoad)
		}
		finally {
			$xmlReaderForLoad.Dispose()
		}

		$attachmentCount = 0
		if ($null -ne $xmlDocument.DocumentElement) {
			$attachmentCount = Expand-EmbeddedAttachments -Node $xmlDocument.DocumentElement -CurrentPath $xmlDocument.DocumentElement.Name -AttachmentOutputDirectory $attachmentOutputDirectory -RelativePrefix $attachmentDirectoryName
		}

		if ($attachmentCount -gt 0) {
			Write-Stage -Group Resolve -Message "Extracted $attachmentCount embedded attachment(s) from '$($xmlFile.Name)'."
		}

		$xmlNodeReader = [System.Xml.XmlNodeReader]::new($xmlDocument)
		$writerSettings = $xslt.OutputSettings.Clone()
		$xmlWriter = [System.Xml.XmlWriter]::Create($htmlOutputPath, $writerSettings)

		try {
			Write-Stage -Group Write -Message "Writing HTML '$htmlOutputPath'."
			$xslt.Transform($xmlNodeReader, $xsltArgs, $xmlWriter)
		}
		finally {
			$xmlWriter.Dispose()
			$xmlNodeReader.Dispose()
		}

		$processedCount++
		Write-Stage -Group Done -Message "HTML created for '$($xmlFile.Name)'."

		if ($shouldPrintPdf) {
			Write-Stage -Group Pdf -Message "Generating PDF '$pdfOutputPath'."
			$htmlUri = [System.Uri]::new($htmlOutputPath).AbsoluteUri
			$arguments = @(
				"--headless",
				"--disable-gpu",
				"--print-to-pdf=$pdfOutputPath",
				$htmlUri
			)

			$process = Start-Process -FilePath $pdfBrowser -ArgumentList $arguments -Wait -PassThru -NoNewWindow
			if ($process.ExitCode -eq 0 -and (Test-Path -LiteralPath $pdfOutputPath -PathType Leaf)) {
				$pdfCount++
				Write-Stage -Group Pdf -Message "PDF created '$pdfOutputPath'."
			}
			else {
				$failedCopyPath = Copy-FailedInfoPathFile -XmlFile $xmlFile -SourceRoot $InfoPathDirectory -FailureRoot $FailedFilesDirectory
				$failedCount++
				Write-ErrorLogEntry -ErrorLogEntries $errorLogEntries -SourceFile $xmlFile.FullName -Message "PDF generation failed. Copied to '$failedCopyPath'."
				Write-Stage -Group Warn -Message "PDF generation failed for '$($xmlFile.FullName)'. Copied to '$failedCopyPath'."
			}
		}
	}
	catch {
		$failedCopyPath = Copy-FailedInfoPathFile -XmlFile $xmlFile -SourceRoot $InfoPathDirectory -FailureRoot $FailedFilesDirectory
		$failedCount++
		Write-ErrorLogEntry -ErrorLogEntries $errorLogEntries -SourceFile $xmlFile.FullName -Message "$($_.Exception.Message) Copied to '$failedCopyPath'."
		Write-Stage -Group Warn -Message "Failed to process '$($xmlFile.FullName)'. Copied to '$failedCopyPath'."
		Write-Stage -Group Error -Message $_.Exception.Message
	}
}

if ($errorLogEntries.Count -eq 0) {
	$errorLogEntries.Add("[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] No processing errors.") | Out-Null
}

$errorLogEntries | Set-Content -LiteralPath $ErrorLogPath -Encoding UTF8

Write-Stage -Group Done -Message "XML files processed to HTML: $processedCount"
Write-Stage -Group Done -Message "Output folder: $OutputDirectory"
Write-Stage -Group Warn -Message "Failed files: $failedCount"
Write-Stage -Group Warn -Message "Failed file copy folder: $FailedFilesDirectory"
Write-Stage -Group Write -Message "Error log: $ErrorLogPath"

if ($shouldPrintPdf) {
	Write-Stage -Group Pdf -Message "PDF files generated: $pdfCount"
}
